=== sMkjke/demo/xml_json/src/test/resources/Message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.sdet-school2021.ru/xml/message"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://www.sdet-school2021.ru/xml/message">

    <xsd:complexType name="Message">
        <xsd:all>
            <xsd:element minOccurs="1" maxOccurs="1" name="messagedate" type="xsd:dateTime"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="surname" type="xsd:string"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="name" type="xsd:string"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="patronymic" type="xsd:string"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="postaladdress" type="xsd:string"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="email" type="xsd:string"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="department" type="tns:Department"/>
            <xsd:element minOccurs="1" maxOccurs="1" name="text" type="xsd:string"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="filename" type="xsd:string"/>
            <xsd:element name="filedata" type="xsd:base64Binary" minOccurs="0" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="Department">
        <xsd:all>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="population" type="xsd:int"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:element name="message" type="tns:Message"/>

</xsd:schema>

=== sMkjke/demo/xml_json/build/resources/main/Message.xml
<?xml version="1.0" encoding="UTF-8"?>

<ss:message xmlns:ss="http://www.sdet-school2021.ru/xml/message"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.sdet-school2021.ru/xml/message Message.xsd">

    <messagedate>${messageDate}</messagedate>
    <surname>${lastName}</surname>
    <name>${firstName}</name>
    <patronymic>${patronymic}</patronymic>
    <postaladdress>Санкт-Петербург, ул.Зенитчиков, д.23, кв. 59</postaladdress>
    <email>${email}</email>
    <department>
        <name>${departmentName}</name>
        <population>${population}</population>
    </department>
    <text>Сообщение, по поводу которого мы должны согласовать наши позиции</text>
    <filename>svid.txt</filename>
    <filedata>0J/RgNC40LzQtdGA</filedata>

</ss:message>

=== sMkjke/demo/xml_json/src/main/resources/ChangedMessage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><ss:message xmlns:ss="http://www.sdet-school2021.ru/xml/message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sdet-school2021.ru/xml/message Message.xsd">

    <messagedate>2022-06-16T22:00:00</messagedate>
    <surname>Yeltcin</surname>
    <name>Boris</name>
    <patronymic>Nikolayevich</patronymic>
    <postaladdress>Санкт-Петербург, ул.Зенитчиков, д.23, кв. 59</postaladdress>
    <email>freedomrussia@ru.ru</email>
    <department>
        <name>${departmentName}</name>
        <population>5</population>
    </department>
    <text>Сообщение, по поводу которого мы должны согласовать наши позиции</text>
    <filename>svid.txt</filename>
    <filedata>0J/RgNC40LzQtdGA</filedata>

</ss:message>
